### PR TITLE
a few tweaks

### PR DESCRIPTION
**Pull request by clinty**

### CODE REVIEW

**Comment by ddssff** [comment]
Thanks, merging.   Do you have a hackage account?  I would like to add you to the maintainers list.

**Comment by clinty** [comment]
Yes, I'm ClintAdams

**Comment by ddssff** [comment]
I've added you to the hackage maintainer group for cabal-debian and debian - enjoy!

**Comment by ddssff** [comment]
I have switched from Debian to Nix for development so you may have full authority to upload to hackage (and github.)

**Comment by clinty** [comment]
Okay, understood.

**Pull request merged**
